#!/usr/bin/ruby
 
require 'mcollective'

include MCollective::RPC


options = rpcoptions do |parser, options|
  parser.define_head "Gitbuilder"
  parser.banner = "Usage: b-buildsite [options] [filters] --site SITE"
 
  parser.on('-s', '--site SITE', 'Site to (re)build from baseline checkout') do |v|
    options[:site] = v
  end
end
 
unless options.include?(:site)
  puts("You need to specify a site with --site")
  exit! 1
end
 
mc = rpcclient("bloatagent", :options => options)

# printrpc mc.git_tag(:site => options[:site])

mc.build_site(:site => options[:site]).each do |spog|
  # puts spog.inspect
  status = spog[:data][:status]
  puts status
end

printrpcstats

mc.disconnect
