#!/usr/bin/ruby
 
require 'mcollective'

include MCollective::RPC


options = rpcoptions do |parser, options|
  parser.define_head "b-taglist"
  parser.banner = "Usage: b-taglist [options] [filters] --repo REPO"
 
  parser.on('-r', '--repo REPO', 'Repo to inspect') do |v|
    options[:repo] = v
  end

  parser.on('-s', '--site SITE', 'Site containing repo') do |v|
    options[:site] = v
  end
end
 
unless options.include?(:repo)
  puts("You need to specify a repo with --repo")
  exit! 1
end
 
mc = rpcclient("bloatagent", :options => options)

# printrpc mc.git_tag(:repo => options[:repo])

mc.git_tag(:repo => options[:repo],:site => options[:site]).each do |spog|
  # puts spog.inspect
  taglist = spog[:data][:tout]
  branchlist = spog[:data][:bout]
  rrepo = spog[:data][:lrep]
  gitrepo = options[:repo]
  printf("Repo: %s (%s)\n[Tags]\n%s\n[/Tags]\n[Branches]\n%s\n[/Branches]\n",gitrepo,rrepo,taglist,branchlist)
end

printrpcstats

mc.disconnect
