#!/usr/bin/ruby 

require 'rubygems'
require 'yaml'
require 'systemu'
require 'stomp'
require 'syslog'
require 'optparse'
require 'socket'
require 'etc'

 
options = {}
version = "3.2"
crlf = /(\r\n|\n\r|\r|\n)/

optparse = OptionParser.new do|opts|
  opts.banner = "Usage: stomp-git.rb [options]"
 
  options[:debug] = false
  opts.on( '-d', '--debug', 'Much output, do not detach' ) do
    options[:debug] = true
  end
 
  options[:configfile] = "/etc/stomp-git/stomp-git.yaml"
  opts.on( '-c', '--config FILE', 'Config is FILE' ) do|file|
    options[:configfile] = file
  end
 
  opts.on( '-h', '--help', 'Display this screen' ) do
    puts opts
        exit
  end
end

optparse.parse!

host_name = Socket::gethostname

if !options[:debug]
  pid = Process.fork
else
  pid = nil
  puts "DEBUG"
  puts "VERSION #{version}"
  puts "CONFIGFILE: #{options[:configfile]}"
end

if pid.nil?
  Signal.trap("TERM") do
    Syslog.info("Terminating.")
        exit
    end

  Signal.trap("HUP") do
    yconfig = YAML.load_file(options[:configfile])
    Syslog.info("Re-read #{options[:configfile]}")
  end

  yconfig = YAML.load_file(options[:configfile])

  puts YAML.dump(yconfig) if options[:debug]

  Syslog.open('stomp-git', Syslog::LOG_CONS, Syslog::LOG_DAEMON)

  stompconnector = yconfig["rserver"] + "?" + yconfig["stomp-options"]

  client = Stomp::Client.new(stompconnector)
  listen_topic = yconfig["listen-topic"]
  report_topic = yconfig["report-topic"]

  repos = yconfig["repo-list"]

  if options[:debug]
    puts repos.inspect
  end

  if client
    Syslog.info("V. #{version} connected to #{listen_topic}")
    puts "V. #{version} connected to #{listen_topic}" if options[:debug]

    client.subscribe "/topic/#{listen_topic}" do |message|
      if message.body == "\n"
        puts "Bodge-beat frame" if options[:debug]
      else
        message.body.each do |mline|
        mkey,mval = mline.split(":",2)
          if mkey == "repo"
            repo = repos["#{mval.strip}"]

            if options[:debug]
              puts "Subject: #{message.headers["subject"]}"
              puts "Message-ID: #{message.headers["message-id"]}"
              puts "Repo: #{mval.strip}"
              puts "--"
              puts message.body
              puts "--"
            end

            if repo.nil?
              puts "Not our repo: #{mval}" if options[:debug]
              break
            end
              
            rdir = repo["repo"]
            if File.exists?(rdir)
              guser = repo["user"]
              begin
                guserinfo = Etc.getpwnam(guser)
              rescue ArgumentError
                eventdetail = host_name + " problem: No such user #{guser}"
                Syslog.info(eventdetail)
                client.publish("/topic/#{report_topic}",eventdetail, {:subject => "Talking to eventbot"})
                puts eventdetail if options[:debug]
                next
              end 

              next if File.readlines('/etc/shells').grep(/#{guserinfo.shell}/).size == 0

              commandline = "/bin/su - #{guser} -c \"cd #{rdir} && /usr/bin/git fetch && /usr/bin/git fetch --tags\""
              puts "Command is #{commandline}" if options[:debug]

              status,stdout,stderr = systemu(commandline, :cwd => rdir, :chomp => true)

              if status != 0
                status_message = " problem: " + stderr
              else
                status_message = " fetched change: #{message.headers["subject"]}"
              end

              eventdetail = host_name + status_message
              eventdetail.gsub!(crlf, " ")

              Syslog.info(eventdetail)
              client.publish("/topic/#{report_topic}",eventdetail, {:subject => "Talking to eventbot"})
              puts eventdetail if options[:debug]

              if repo["mode"] == "puppetmaster"
                s1,s2,s3 = message.headers["subject"].split(' ',3)
                branch = s2.sub('refs/heads/','')
                pdir = repo["target"]
                wdir = pdir + "/" + branch

                puts "Branch: #{branch} (#{s2})" if options[:debug]
                puts "Workdir: #{wdir}" if options[:debug]
              
                if !File.exists?(wdir)
                  Dir.mkdir(wdir)
                  File.chown(guser.uid,guser.gid,wdir)
                end

                commandline = "/bin/su - #{guser} -c \"cd #{rdir} && /usr/bin/git --work-tree=#{wdir} checkout -f origin/#{branch}\""
                puts "Command is #{commandline}" if options[:debug]

                status,stdout,stderr = systemu(commandline, :cwd => rdir, :chomp => true) 

                if status != 0
                  status_message = " PM problem: " + stderr
                else
                  status_message = " PM wrote branch #{branch} into #{wdir} "
                end

                eventdetail = host_name + status_message
                eventdetail << "#{stdout}" if options[:debug]
                eventdetail.gsub!(crlf, " ")

                Syslog.info(eventdetail)
                client.publish("/topic/#{report_topic}",eventdetail, {:subject => "Talking to eventbot"})
                puts eventdetail if options[:debug]
              end

              if repo["mode"] == "dangerous"

                commandline = "/bin/su - #{guser} -c \"cd #{rdir} && /usr/bin/git checkout origin/master\""
                puts "Command is #{commandline}" if options[:debug]

                status,stdout,stderr = systemu(commandline, :cwd => rdir, :chomp => true)

                if status != 0
                  status_message = " problem: " + stderr
                else
                  status_message = " checkout: "
                end

                eventdetail = host_name + status_message + " (#{repo["mode"]})"
                eventdetail << " #{stdout}" if options[:debug]
                eventdetail.gsub!(crlf, " ")

                Syslog.info(eventdetail)
                client.publish("/topic/#{report_topic}",eventdetail, {:subject => "Talking to eventbot"})
                puts eventdetail if options[:debug]
              end

              if repo["mode"] == "trusting"
                wdir = repo["target"]

                commandline = "/bin/su - #{guser} -c \"cd #{rdir} && /usr/bin/git --work-tree=#{wdir} checkout -f origin/master\""
                puts "Command is #{commandline}" if options[:debug]

                status,stdout,stderr = systemu(commandline, :cwd => rdir, :chomp => true)

                if status != 0
                  status_message = " problem: " + stderr
                else
                  status_message = " checkout: "
                end

                eventdetail = host_name + status_message + " (#{repo["mode"]})"
                eventdetail << " #{stdout}" if options[:debug]
                eventdetail.gsub!(crlf, " ")

                Syslog.info(eventdetail)
                client.publish("/topic/#{report_topic}",eventdetail, {:subject => "Talking to eventbot"})
                puts eventdetail if options[:debug]
              end

            else
              eventdetail = "Repo in config but not in filesystem: #{mval}"
              Syslog.info(eventdetail)
              client.publish("/topic/#{report_topic}",eventdetail, {:subject => "Talking to eventbot"})
              puts eventdetail if options[:debug]
            end
          end
        end
      end 
    end

    client.join
    client.close
  end

else
  Process.detach(pid)
end
