#!/bin/bash
# unicorn-github-stomp
#                        via unicorn.
#
# Authors:               Richard Crowley 
#                        Naresh V. 
#
#    Modified for Debian usage by Matt Carroll
#	Cracked & Trained by JHR
#    
#
### BEGIN INIT INFO
# Provides:          unicorn-github-stomp
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: unicorn-github-stomp
# Description:       unicorn-github-stomp
### END INIT INFO


USER=rubyapps
APPNAME=github-stomp

RETVAL=0
WORKDIR="/data/$APPNAME"
DAEMON="$WORKDIR/bin/unicorn"
DAEMON_OPTS="-D -c $WORKDIR/unicorn.conf"

lockfile="/var/lock/unicorn-$APPNAME"
pidfile="/var/run/unicorn/$APPNAME.pid"


start() {
    	su -l $USER -c "$DAEMON $DAEMON_OPTS"
    	RETVAL=$?
    	[ $RETVAL -eq 0 ] && touch "$lockfile"
    	echo
    	return $RETVAL
}

stop() {
    kill `cat $pidfile`
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f "$lockfile"
    return $RETVAL
}

restart() {
    stop
    sleep 1
    start
    RETVAL=$?
    echo
    [ $RETVAL -ne 0 ] && rm -f "$lockfile"
    return $RETVAL
}

condrestart() {
    status
    RETVAL=$?
    [ $RETVAL -eq 0 ] && restart
}

status() {
    ps ax | egrep -q "unicorn (worker|master)"
    RETVAL=$?
    return $RETVAL
}

usage() {
    echo "Usage: $0 {start|stop|restart|status|condrestart}" >&2
    return 3
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    condrestart)
        condrestart
        ;;
    status)
        status
        ;;
    *)
        usage
        ;;
esac

exit $RETVAL

